name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and Release Angular
        run: ./bin/release.sh
      - name: Deploy to Github Pages
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "[actions] update GithubPages contents"
          git push origin master
